### ISSUE TITLE
Fix vote link

### ISSUE THREAD

**Issue by thgaskell** [Hackbit/nko2017-nodenodenode#65]
Idk if the script I used from the team page is broken or what. There's a missing image that's not showing up:

![image](https://user-images.githubusercontent.com/844945/32697718-f0176246-c73a-11e7-9114-724d424242ea.png)
![image](https://user-images.githubusercontent.com/844945/32697722-f5ecd444-c73a-11e7-8eee-0d94fd0e6ad8.png)

The link _is_ working though so it's all good :man_shrugging:

**Comment by alextebbs** [comment]
I have no idea either, i have to assume its trying to load the node knockout logo. 
![screen shot 2017-11-12 at 3 33 50 am](https://user-images.githubusercontent.com/433327/32698412-629c4952-c75a-11e7-8c28-1dc55fb4e542.png)
Putting the script in an empty codepen to try to repro the issue gives me: 
![screen shot 2017-11-12 at 3 35 43 am](https://user-images.githubusercontent.com/433327/32698431-997989c6-c75a-11e7-9334-9455d9fc92a8.png)

no work.

**Comment by thgaskell** [comment]
Huh, it seems to have resolved itself. JustWorks!™
![image](https://user-images.githubusercontent.com/844945/32703468-7baaed8c-c79a-11e7-825d-25a1248e85be.png)
